#!/bin/bash
#source: https://askubuntu.com/questions/151513/reload-gtk-3-0-theme
key=org.mate.interface

theme=$(gsettings get $key gtk-theme)
echo "Found theme: $theme"
gsettings set $key gtk-theme ''
echo "Resetting..."
gsettings set $key gtk-theme $theme

#make sure the panel refreshes so the clock isn't stopped:
killall mate-panel
