#!/bin/bash
source ~/.bashrc #source main bashrc so we can add to the environment outside of repo
source ${BASH_SOURCE%/path/*}/config/bashrc

REQUEST=$1
shift

case "${REQUEST}" in
  POST)
      if [ ! -f ${1} ];then
        error "No json file at '$1'"
      fi
      json="-H 'Content-Type: application/json' -d '@${1}'"
      shift
    ;;
  GET|DELETE|PUT)
    ;;
  *)
      error "Unsupported request: ${REQUEST}"
    ;;
esac

eval curl -n -X $REQUEST $json --silent "${JIRA}/$@" | python -mjson.tool
