#!/bin/bash
#Kubernetes (k8s) helper scripts

if [ $# -lt 1 ];then
  echo -e "\033[1mUsage:\033[0m \033[33;1m${0##*/}\033[0m [\033[32;1mresource\033[0m] [\033[36;1maction\033[0m]"
  grep -Eo '^##.*$' $BASH_SOURCE | \
  while read section
  do
    echo ""
    echo -e "  \033[1m${section#\#\#}\033[0m"
    sed -n "/^${section}\$/,/^##/ p" $BASH_SOURCE | grep -Eo '[^ (]+\)\s+#.*$' | \
    while read help
    do
      params=${help#*#}
      params=${params%%#*}
      if [ -z "${params}" ];then
        params="$(grep -A 1 -F "${help}" $BASH_SOURCE | tail -n 1 | grep 'trap' | grep -Eo '\[[^]]*\]' | tr $'\n' ' ')"
      fi
      col=$(printf "\033[33;1m%s\033[0m %s" "${help%%)*#*}" "${params}")
      printf "    %-60s %s\n" "${col}" "${help##*#}"
    done
  done
  echo ""
  exit
fi

case "$(uname -s)" in
  Darwin) #Mac
      TMP=/tmp
      alias md5sum=md5
      alias sedi="sed -i ''"
      alias tac="tail -r"
      alias browser="open"
    ;;
  Linux)
      TMP=/dev/shm
      alias sedi="sed -i"
      alias browser="python -m webbrowser"
    ;;
  *)
      echo "Unsupported host OS"
      exit 1
    ;;
esac

PID=$$
export TMP=${TMP}/${PID}
mkdir ${TMP}

trap "rm -rf ${TMP} >/dev/null 2>&1" EXIT
trap "rm -rf ${TMP} >/dev/null 2>&1;kill -- -$$" SIGINT

IFS='|'
shopt -s expand_aliases extglob

#FUNCTIONS

function kate_namespaces() {
  local IFS=$'\n'
  local resource=$1
  shift
  local action=$1
  shift

  local STDOUT=${TMP}/stdout
  local OUTPUT=${TMP}/output
  for namespace in $(kubectl get namespace -o=name | grep -v 'namespaces/kube-' | sed 's/namespaces\///')
  do
    echo -e "\033[34m$namespace\033[0m" > $STDOUT
    for object in $(kubectl -n $namespace get $resource -o=name)
    do
      echo -e "  \033[32m$object\033[0m" >> $STDOUT
      case "${action}" in
        get|describe)
            kubectl -n $namespace $action $object > $OUTPUT #| sed -n '/^Events:$/,$ p'
          ;;
        event|events)
            kubectl -n $namespace describe $object | sed -n '/^Events:$/,$ p' > $OUTPUT
          ;;
      esac
      if [ -s $OUTPUT ];then
        cat $STDOUT
        cat $OUTPUT | sed 's/^/    /'
      fi
      rm $STDOUT $OUTPUT
    done
  done
}

export -f kate_namespaces

#MAIN

echo -e "\033[33;1m${0##*/} $(xargs <<< "$@")\033[0m"

resource="$1"
shift
action="$1"
shift



##All-Namespace Actions:
case "${action}" in
  get|describe|event|events) ##Show information from resources
        kate_namespaces $resource $action
      exit
    ;;
  *)
      echo -e "\033[33mno such action:\033[0m $action"
      exit
    ;;
esac

