#!/bin/bash
#Testing which parameters are overwritten
#Usage:  overrides 1 2 3 4 5 6 7 8 9 10
#Output: 1 2 3 CHANGED 5 6 prefix:CHANGED
#See PARAMETER OVERWRITING in params.sh

source ~/.bashrc #source main bashrc so we can add to the environment outside of repo
source ${BASH_SOURCE%/path/*}/config/bashrc

TIMESTAMP=false

function param() {
  echo -n CHANGED
}

##Override Windows paths:
#function param() {
#  echo -n /mnt/c/Users/UserName/Downloads/apache-tomcat-10.1.40-windows-x64/apache-tomcat-10.1.40/temp/${1##*temp}
#}

set -- "${@:1:3}" "$(param $4)" "${@:5:2}" "prefix:$(param $7)"

echo $@
