#!/bin/bash
#Testing which parameters are overwritten
#Usage:  overrides 1 2 3 4 5 6 7 8 9 10
#Output: 1 2 3 CHANGED 5 6 prefix:CHANGED
#See PARAMETER OVERWRITING in params.sh

source ~/.bashrc #source main bashrc so we can add to the environment outside of repo
source ${BASH_SOURCE%/path/*}/config/bashrc

TIMESTAMP=false

function param() {
  echo -n CHANGED
}

##Override Windows paths:
function param() {
  prefix=${1%%C:*}
  echo -n ${prefix}/mnt/c/Users/UserName/apache-tomcat-10.1.40-windows-x64/temp/${1##*temp}
}

##Hard coded:
#set -- "${@:1:3}" "$(param $4)" "${@:5:2}" "oci-dir:$(param $7)"

##Detected:
ARGS=()
for i in $(seq 1 $#)
do
  echo "$i: ${!i}"
  case "${!i}" in
    *C:*apache-tomcat*temp*)
        echo "  override"
        ARGS[$i]=$(param ${!i})
      ;;
    *)
        ARGS[$i]=${!i}
      ;;
  esac
done
set -- ${ARGS[*]}

echo $@
