#!/bin/bash

case "$(uname -s)" in
  Darwin) #Mac
      echo -e "\033[31munsupported OS for this script\033[0m"
      exit 1
    ;;
  Linux)
    ;;
esac

shopt -s expand_aliases

IFS=$'\n'
while read -r line
do
  path=${line%/*}
  file=${line##*/}
  old="${line}"
  when=$(exif -mt DateTimeOriginal ${line})
  if [ "$?" -ne 0 ];then
    echo -e "\033[33musing timestamp\033[0m"
    new="${path-.}/$(stat "${line}" -c '%y' | cut -d'.' -f1) ${file}"
  else
    when=${when/:/-}
    when=${when/:/-}
    new="${path-.}/${when} ${file}"
  fi
  printf "\033[32m%-30s\033[0m %s\n" "${old}" "${new}"
  mv -n "${old}" "${new}"
done < <(find . -type f)
