#!/bin/bash

IFS=$'\n'
while read -r line
do
  path=${line%/*}
  file=${line##*/}
  old="${line}"
  #new="${path-.}/$(stat "${line}" -c '%y' | cut -d'.' -f1) ${file}"
  when=$(exif -mt DateTimeOriginal ${line})
  if [ "$?" -ne 0 ];then
    echo -e "\033[31mskipping\033[0m ${line}"
    continue
  fi
  when=${when/:/-}
  when=${when/:/-}
  new="${path-.}/${when} ${file}"
  printf "\033[32m%-30s\033[0m %s\n" "${old}" "${new}"
  mv -n "${old}" "${new}"
done < <(find . -type f)
