#!/bin/bash

RESOURCES=${BASH_SOURCE%/path/*}
if echo ${RESOURCES} | grep -q ${HOME};then
  RESOURCES="~${RESOURCES##$HOME}"
fi

echo "Found resources directory: ${RESOURCES}"

case "$(uname -s)" in
  Darwin) #Mac
      export BASHRC=~/.bash_profile
    ;;
  Linux)
      export BASHRC=~/.bashrc
    ;;
esac


if grep -q "source ${RESOURCES}/config/bashrc" ${BASHRC};then
  echo "  present in ${BASHRC}"
else
  tee -a ${BASHRC} <<< "source ${RESOURCES}/config/bashrc"
  echo "  added to ${BASHRC}"
fi

echo "source resources..."
source ${BASH_SOURCE%/path/*}/config/bashrc

log "Installing packages..."

case "$(uname -s)" in
  Darwin) #Mac
      ensure -p coreutils greadlink gexpr
      ensure -p gnu-sed gsed
      ensure -p grep ggrep
      ensure csshx dos2unix colordiff bash-completion the_silver_searcher kubernetes-helm
    ;;
  Linux)
      ensure \
        python \
        geany
      #Missing: helm, kubectl kops
      case "${PACKAGER}" in
        rpm)
            ensure \
              subversion-perl \
              epel-release \
              the_silver_searcher \
              cssh
          ;;
        deb)
            #Missing: cssh
            ensure \
              net-tools \
              libsvn-perl \
              silversearcher-ag
          ;;
      esac
    ;;
esac

#TODO: check on linux platforms
ensure \
  ansible \
  jq \
  jo \
  nmap \
  socat \
  tee \
  telnet \
  watch \
  wget

log "Check for krew..."
if [ -d ~/.krew/bin ];then
  log "  already installed"
else
  (
    set -x; cd "$(mktemp -d)" &&
    curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/krew.{tar.gz,yaml}" &&
    tar zxvf krew.tar.gz &&
    KREW=./krew-"$(uname | tr '[:upper:]' '[:lower:]')_amd64" &&
    "$KREW" install --manifest=krew.yaml --archive=krew.tar.gz &&
    "$KREW" update
  )
  log "krew installed"
fi

log "Check for kubectl exec-as plugin..."
if kubectl krew list | grep -q exec-as;then
  log "  already installed"
else
  log "  installing..."
  run kubectl krew install exec-as
fi

log "DONE"

<<COMMENT1
OPTIONAL:
  autoconf
  du
  hicolor-icon-theme
  mariadb
  sqlite
  sendemail

TODO:
  Mac:
    geany
    macports:
      gawk
      tidy
      vnc
  All:
    kubetail
    krew
    docker
    minikube
    yq

COMMENT1
