#!/bin/bash

if [ $# -lt 1 ]; then
	echo "Usage: ${0##*/} [pid]"
	echo "  Trails a bash process for keystrokes."
	exit
fi

regex=".*\"(.*)\".*)"

sudo strace -ff -e trace=write -e write=1,2 -p $1 2>&1 | \
while read pipe
do
	[[ $pipe =~ $regex ]]
  key="${BASH_REMATCH[1]}"
  #echo "Pipe: \"$pipe\""
	echo -e "Key: \"$key\""
done
