#!/bin/bash

case "$(uname -s)" in
  Darwin) #Mac
      echo -e "\033[31munsupported OS for this script\033[0m"
      exit 1
    ;;
  Linux)
    ;;
esac

shopt -s expand_aliases
mkdir out
for file in *.MOV
do
  echo -e "\033[32m${file}\033[0m"
  ffmpeg \
    -i "${file}" \
    -vf "scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2,setsar=1" \
    "out/${file}"
  echo -e "\033[33mout/${file}\033[0m"
done


