#!/bin/bash
mkdir {acknowledgement,annoyed,selected}
mv *piss*.wav annoyed/
mv *what*.wav selected/
mv *yessr*.wav acknowledgement/

cd acknowledgement
rename 's/^[^\d]*//' *.wav

cd ../selected
rename 's/^[^\d]*//' *.wav

cd ../annoyed
rename 's/^[^\d]*//' *.wav

cd ../
