#!/bin/bash
source ~/.bashrc #source main bashrc so we can add to the environment outside of repo
source ${BASH_SOURCE%/path/*}/config/bashrc

tmp=/dev/shm/ytmp3.$$

case "$(uname -s)" in
  Darwin) #Mac
      echo -e "\033[31munsupported OS for this script\033[0m"
      exit 1
    ;;
  Linux)
    ;;
esac

shopt -s expand_aliases

url="$1"
if [ -z "${url}" ];then
  echo -e "${0##*/} [url]"
  echo -e "  Download youtube video as mp4"
  exit
fi

#See OUTPUT TEMPLATE: https://github.com/yt-dlp/yt-dlp#output-template
#-F list formats
#-f "bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4]"
#--recode-video or --remux-video "aac>m4a/mov>mp4/mkv"
yt-dlp --check-formats -o '%(title)s.%(ext)s' "${url}"
green "Converting webm and mkv to mp4"
tomp4 *.webm *.mkv
