#!/bin/bash
source ${BASH_SOURCE%/path/*}/config/bashrc

case "$(uname -s)" in
  Darwin) #Mac
      echo -e "\033[31munsupported OS for this script\033[0m"
      exit 1
    ;;
  Linux)
    ;;
esac

shopt -s expand_aliases

url="$1"
if [ -z "${url}" ];then
  echo -e "${0##*/} [url]"
  echo -e "  Download youtube link as audio and convert to mp3"
  exit
fi

tmpdir
cd ${tmp}

#output format: yt-dlp -o '%(title)s.%(ext)s'
#See OUTPUT TEMPLATE: https://github.com/yt-dlp/yt-dlp#output-template

#Try to download only the audio first:
yt-dlp -f 251 "${url}"
if [ $? -gt 0 ];then
  #Download video:
  yt-dlp "${url}"
fi

webm="$(ls)"
if [ ! -f "${webm}" ];then
  echo "Cannot find file '${webm}'"
  exit
fi

ffmpeg -i "${webm}" -vn -ab 128k -ar 44100 -y "${CWD}/${webm% [*}.mp3"
if [ $? -gt 0 ];then
  echo -e "ERROR converting video"
  exit
fi

echo -e "Output: '${webm% [*}.mp3'"
