#!/bin/bash

tmp=/dev/shm/ytmp3.$$

case "$(uname -s)" in
  Darwin) #Mac
      echo -e "\033[31munsupported OS for this script\033[0m"
      exit 1
    ;;
  Linux)
    ;;
esac

shopt -s expand_aliases

url="$1"
if [ -z "${url}" ];then
  echo -e "${0##*/} [url]"
  echo -e "  Download youtube link as audio and convert to mp3"
  exit
fi

#output format: yt-dlp -o '%(title)s.%(ext)s'
#See OUTPUT TEMPLATE: https://github.com/yt-dlp/yt-dlp#output-template
yt-dlp -f 251 "${url}" 1> >(tee $tmp) 2>&1
result=$(<$tmp)
webm=$(echo -e "${result}" | grep -Po 'Destination: .*$' | cut -d' ' -f2-)
ffmpeg -i "${webm}" -vn -ab 128k -ar 44100 -y "${webm% [*}.mp3"
if [ $? -gt 0 ];then
  echo -e "ERROR converting video"
  exit
fi
rm -f "${webm}" $tmp
echo -e "Output: '${webm%-*}.mp3'"