#!/bin/bash
#INCLUDE from ~/.bashrc: source ~/projects/resources/config/bashrc

#includes .bashrc, .bash_aliases, and any other hidden scripts in this directory:
for bash in ~/projects/resources/config/.{_,}[!_.]*
do
  #echo "source $bash"
  source $bash
done

#remove duplicates: https://superuser.com/questions/449636/path-is-filled-with-duplicates (calling 'resource' re-adds paths)
PATH="$(perl -e 'print join(":", grep { not $seen{$_}++ } split(/:/, $ENV{PATH}))')"