#!/bin/bash
#INCLUDE from ~/.bashrc: source ~/projects/resources/config/bashrc

#includes .bashrc, .bash_aliases, and any other hidden scripts in this directory:
for bash in ~/projects/resources/config/.[!.]*
do
	source $bash
done
